server:
  port: 8080
  servlet:
    context-path: /user-management

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/employee_manage"
    username: root
    password: "hoađôđăđ̀Â"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  spring:
    security:
      debug: true
